FROM php:7.4-apache

# Install dependencies
RUN apt-get update && apt-get install -y -qq \
    apt-utils \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    libonig-dev \
    libzip-dev \
    libmagickwand-dev \
    default-mysql-client \
    zip \
    unzip \
    cron \
    imagemagick \
    libheif-examples \
    && docker-php-ext-configure gd \
        --with-freetype \
        --with-jpeg \
    && docker-php-ext-install -j$(nproc) \
        gd \
        mbstring \
        zip \
        mysqli \
        pdo \
        pdo_mysql \
    && pecl install imagick \
    && docker-php-ext-enable imagick mysqli pdo_mysql \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Apache modules
RUN a2enmod rewrite headers expires

# Timezone
RUN echo "date.timezone=Asia/Jakarta" > /usr/local/etc/php/conf.d/timezone.ini

# Working directory
WORKDIR /var/www/html

# Copy php.ini
COPY php.ini /usr/local/etc/php/

# Permission
RUN chown -R www-data:www-data /var/www/html
